### PR TITLE
希望能合并

### PR DESCRIPTION
**Pull request by wartaiwan24**
我之前提交的pull的确有些问题，复制我收藏的一些域名时出错了，已经存在的域名也复制了一遍，编辑时一不小心还把一些其它域名的一部分删掉了，所以我就把pull关掉了。还请您在审查一下。我提交的域名包含360广告联盟、腾讯、小米、番茄小说等等的一些广告域名。我刚刚又一不小心删掉了一些域名，幸好及时发现，已经补回去了，我这次提交的pull才是正确的，之前的pull已关闭

### CODE REVIEW

**Comment by wartaiwan24** [comment]
被我删掉的mine.baidu.com已经补回去了

**Comment by TG-Twilight** [comment]
Many of the domains you submitted do not meet our standards and requirements. While there are some merits, they mostly disrupt the normal browsing experience for users.

For example, I just randomly checked:
'wot.360.cn', which is the official website for the game World of Tanks.
'360kuai.com' is the 360 news website, not an advertisement.
But both of the above were incorrectly added by you.
There are also some invalid domains.

Also, some domains already exist in our block list.

This is very irresponsible behavior. Please carefully check your block list before submitting it!

Everyone is very busy. Don't frequently submit PRs/issues and waste other people's time before you have checked it yourself!

**Comment by TG-Twilight** [comment]
If you are unable to determine what content should be blocked, it is recommended that you directly submit an issue or join our official group for feedback. There are volunteers who can provide support.

**Comment by TG-Twilight** [comment]
不是打击你，是你提交的这个我们真的没法合并。

我们理解你可能讨厌360公司，事实上，对于他们的大部分产品确实我们也不喜欢。

但你绝对不能因为这份厌恶，而去直接封锁一些不应该被封锁的域名。

我们接受的域名类型有：

广告、过分的追踪链接、过度的数据采集、恶意网站（例如涉及诈骗）等。

**Pull request closed without merging**
